title: "Frank Ygnacio Rosas"
description: "Quantitative Finance & Investment Professional"
permalink: pretty
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
